COMBO_ENABLE           = no
MOUSEKEY_ENABLE = no      # Mouse keys
EXTRAKEY_ENABLE = no      # Audio control and System control
# SWAP_HANDS_ENABLE = yes # doesn't work
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = yes
